Asterix/Example_param_file.ini, Asterix/InstrumentSimu_functions.py, Asterix/Main_EFC_THD.py, Asterix/Param_configspec.ini, Asterix/WSC_functions.py
Science image can be polychromatic
Estimation and correction is still monochromatic (next change to come)
=> Chromatism

.gitignore, Asterix/Example_param_file.ini, Asterix/InstrumentSimu_functions.py, Asterix/Main_EFC_THD.py, Asterix/Param_configspec.ini, Asterix/WSC_functions.py, Asterix/fits_functions.py, Asterix/phase_amplitude_functions.py, Asterix/processing_functions.py, Asterix/propagation_functions.py
Classical Lyot but also large cleaning. FQPM is back with fft now working in polychromatic.
Lot and lot of cleaning to make the code more general to avoid copy and past of large portions of the code that can be coded in a single place
=> Calssical lyot

Asterix/Example_param_file.ini, Asterix/InstrumentSimu_functions.py, Asterix/Main_EFC_THD.py, Asterix/WSC_functions.py, Asterix/fits_functions.py, Asterix/processing_functions.py, Asterix/propagation_functions.py
Lot of cleaning to better use the thdstructure (varaible removed from function).
CAREFUL, I have tried to remove the 1+ probe in createvectorprobes and it definitely does not work. 
Remove apply_on_DM and create a function voltage_to_phase in DM class. 
Should we only use voltages to talk to the DMs instead of phase? (for example when using testbed.todetector). This would be more general and closer to the truth of the testbed.
=> Clean with thdstructure johan

Asterix/Main_EFC_THD.py
Correction of small things (name of estimation is now converted to lowercase, and so on)
=> Small modif r ga

Asterix/Example_Run_Asterix.py, Asterix/Example_param_file.ini, Asterix/InstrumentSimu_functions.py, Asterix/Main_EFC_THD.py, Asterix/Optical_System_functions.py, Asterix/Param_configspec.ini, Asterix/WSC_functions.py, Asterix/estimator.py, Asterix/fits_functions.py, Asterix/phase_amplitude_functions.py, Asterix/processing_functions.py, Asterix/propagation_functions.py, Asterix/tuto_asterix_model.py, todo.txt
In practice changes are transparent for the correction, i did not touche the optical side, just the python organization 
Big changes:
I finally defined my concatenation function for Optical System. We can now change the system completely transparently for the code, this is ready for Roman ! 
Initializaiton of the estimation class.
The Example_run_asterix is now a big test file that you can run when you want to push to master. You can comment part of it to go faster but you nedd to run it fully before push ! 
The tutorial is ready, you can have a look !
=> Class estimator

Asterix/Example_Run_Asterix.py, Asterix/Example_param_file.ini, Asterix/Main_EFC_THD.py, Asterix/Optical_System_functions.py, Asterix/Param_configspec.ini, Asterix/WSC_functions.py, Asterix/corrector.py
a lot of cleaning of the correction class
the basis is now done at a single position (there fore which in pup in now only use inside the basis) and can be replaced easily by others when needed.
not sure mis registration is currently workin well!
=> Clean correc bis

Asterix/Example_Run_Asterix.py, Asterix/Main_THD.py, Asterix/Optical_System_functions.py, Asterix/WSC_functions.py, Asterix/corrector.py, Asterix/processing_functions.py
incorporated Raphael comments + automatic formatting
=> incorporated Raphael comments + automatic formatting

Asterix/Example_Run_Asterix.py, Asterix/Example_param_file.ini, Asterix/Main_THD.py, Asterix/Optical_System_functions.py, Asterix/Param_configspec.ini, Asterix/WSC_functions.py, Asterix/correction_loop.py, Asterix/corrector.py, Asterix/estimator.py, Asterix/phase_amplitude_functions.py, Asterix/propagation_functions.py, Asterix/tuto_asterix_model.py
add rotation,
new oversampling pupil plane factor parameter to avoid aliasing due to out of PP DM.
EFC 2DM Work on the testbed with this version
=> New thd modif johan

Asterix/Example_param_file.ini, Asterix/Optical_System_functions.py, Asterix/corrector.py, Asterix/fits_functions.py, Asterix/propagation_functions.py, Asterix/tuto_asterix_model.py
- correction in mft -> now the MFt of a clear symetrical pupil is entirely real. 
- correction in Babinet -> there was an error in the propagation which made the mask smaller than it was actaully
- lyot radius in pixel is not an integer
- other small corrections
- clean and comment
-> Classical Lyot almost agree with hcipy (resolution and general shape of post-corono PSF are ok). 10% difference in contrast probably due to a different way to normalize the PSF (to investigate). 
-> Classical Lyot and HLC are now converging a lot deeper -> probably working
=> Test and dvp new coronos

Asterix/Optical_System_functions.py, Asterix/processing_functions.py, Asterix/tuto_asterix_model.py
use Medhi function to shift actuators. 
Clean stuff a bit also
=> Add ft subpixel shift

README.md, environment.yml, setup.py
Up to this point, the installation instructions in the PDF documentation lists manually how to create the conda environment for Asterix. In this PR, I added an `environment.yml` file that can be run to do that without having to manually specify the conda dependencies. I also removed the duplicated dependencies from `setup.py` so that there are no double installations between conda and pip.
I also updated the readme to have quick instructions for the installation.
=> Add conda environment file

Asterix/tests/test_parameter_file.py, environment.yml, setup.py
I am adding a first pytest to set up an example in case there are other tests in the future that need to find a place. Currently no tests are deployed automatically but it's handy to at least have them set up to be able to run them offline.
=> Add first pytest

Asterix/Example_param_file.ini, Asterix/Optical_System_functions.py, Asterix/Param_configspec.ini, Asterix/tests/test_coronagraph.py, Asterix/tuto_asterix_model.py, notebooks/beginner-tutorial_optical-components-and-systems.ipynb
- I took the existing tutorial in form of a script `tuto_asterix_model.py` [here](https://github.com/johanmazoyer/Asterix/blob/94c53ed370d66e138b3fe526693eb11709d2710d/Asterix/tuto_asterix_model.py) and created a notebook version of it.
- I fixed up the scripted tutorial itself
- I made the file output in the phase generation function temporary - I think it's useful to be able to simulate things without having to worry about file I/O.
- I added a pytest for the perfect coronagraph, which is the default in the example configuration file
=> Create tutorial notebook

notebooks/beginner-tutorial_optical-components-and-systems.ipynb
The tutorial merged with #54 was not fully runnable, this PR fixes that.
=> Fix errors in tutorial left over from #54.

Asterix/THD_quick_invert.py, Asterix/WSC_functions.py, Asterix/correction_loop.py, Asterix/corrector.py, Asterix/estimator.py, Asterix/main_THD.py, Asterix/optical_systems.py, Asterix/phase_amplitude_functions.py, Asterix/save_results.py, Asterix/tests/test_coronagraph.py, Asterix/tuto_asterix_model.py, notebooks/beginner-tutorial_optical-components-and-systems.ipynb, source/correction.rst, source/create_my_testbed.rst, source/index.rst
Rename some functions to make it easier to discern between functions and classes.
=> Function renaming

Asterix/THD_quick_invert.py, Asterix/WSC_functions.py, Asterix/correction_loop.py, Asterix/corrector.py, Asterix/estimator.py, Asterix/example_run_asterix.py, Asterix/main_THD.py, Asterix/optical_systems.py, Asterix/phase_amplitude_functions.py, Asterix/processing_functions.py, Asterix/propagation_functions.py, Asterix/save_and_read.py, Asterix/save_results.py, Asterix/tests/test_coronagraph.py, Asterix/tests/test_parameter_file.py, Asterix/tuto_asterix_model.py, notebooks/beginner-tutorial_optical-components-and-systems.ipynb, source/correction.rst, source/create_my_testbed.rst, source/index.rst, source/run_asterix.rst
Cleaning up a little bit by renaming scripts.
Needs #61 to be merged first.
=> Rename some scripts and modules

README.md
Add contributing guidelines to README file.
=> Add contributing guidelines to README

Asterix/optics/coronagraph.py, Asterix/optics/phase_amplitude_functions.py, Asterix/optics/propagation_functions.py, Asterix/optics/pupil.py, Asterix/tests/test_coronagraph.py, Asterix/utils/gaussians.py, Asterix/utils/processing_functions.py
This PR implements @rgalicher's function from IDL that calculates the phase mask for the [2020 wrapped vortex coronagraph](https://ui.adsabs.harvard.edu/abs/2020A%26A...635A..11G/abstract).
=> Use wrapped vortex coronagraph with analytically defined phase mask.

Asterix/optics/optical_systems.py
Requested by @johanmazoyer in #71.
=> Change "throughput" to "transmission" where it is calculated.

Asterix/optics/phase_amplitude_functions.py, Asterix/tests/test_propagations.py, Asterix/tests/test_pupil.py, notebooks/zoom-in_sampling_coro.ipynb
This PR is modifying the roundpupil function:
- remove the no_pixel keyword that was confusing
- create a grey_pup_bin_factor parameter. if grey_pup_bin_factor > it does a grey pupil, if grey_pup_bin_factor =1, normal one. Added Value errors to make it run smoothly
=> replace better version of roundpupil

Asterix/optics/coronagraph.py, Asterix/optics/deformable_mirror.py, Asterix/optics/optical_systems.py, Asterix/optics/phase_amplitude_functions.py, Asterix/optics/pupil.py, Asterix/optics/testbed.py, Asterix/utils/hci_metrics.py, Asterix/utils/processing_functions.py, Asterix/utils/save_and_read.py, Asterix/wfsc/correction_loop.py, Asterix/wfsc/corrector.py, Asterix/wfsc/estimator.py, Asterix/wfsc/thd_quick_invert.py, Asterix/wfsc/wf_control_functions.py
Replacing all basic exceptions `Exception` with an appropriate built-in exception.
https://docs.python.org/3/library/exceptions.html
https://realpython.com/python-exceptions/
=> Use built-in exceptions that are not just `Exception`

Asterix/optics/phase_amplitude_functions.py
Fix problem in roundpupil that was bugging with non integer radius. Very good argument to use test before PRs :-)
=> fix round pupil possible with non integer rad

notebooks/beginner-tutorial_optical-components-and-systems.ipynb
=> Fix THD2 class import.

Asterix/wfsc/maskDH.py
DH_shape and DH_side (in case 'DH_shape' = 'circle') now raise an error if the parameters are not correct.
=> Add Value Error in dh mask

Asterix/optics/deformable_mirror.py, notebooks/dm_displays.ipynb, notebooks/image_with_thd2.ipynb, notebooks/individual_plane_display.ipynb, notebooks/parity_checks.ipynb, notebooks/work_with_DH_images.ipynb
This PR just adds some notebooks I thought would be useful on the repo. And fixes a single docstring.
@johanmazoyer I don't think there's a need to review all the notebooks in details but it's up to you.
=> Add notebooks for orientation checks and model inspection

Asterix/Example_param_file.ini, Asterix/optics/deformable_mirror.py, Asterix/tests/param_file_tests.ini, Asterix/tests/test_coronagraph.py, Asterix/tests/test_testbed.py, Asterix/tests/test_wfsc.py, Asterix/wfsc/corrector.py, Asterix/wfsc/estimator.py, Asterix/wfsc/wf_control_functions.py, notebooks/dm_displays.ipynb, notebooks/image_with_thd2.ipynb, notebooks/individual_plane_display.ipynb, notebooks/parity_checks.ipynb, notebooks/work_with_DH_images.ipynb
Fix a small error introduced for perfect estimation when I disantangle testbed wl and estimation wl.
=> error in multichrom correction with perfect estimate

Asterix/optics/deformable_mirror.py, Asterix/optics/testbed.py, Asterix/utils/processing_functions.py, Asterix/wfsc/wf_control_functions.py
A mix of a few things:
- a small modifs of a function docstring that was wrong
- a minor improvement in the matrix measurement. I tried to change completely the matrix (so that it could be parallelized) but I did not succeed so it is now commented if I think about something else.
-
=> Small error in docs

Asterix/main_THD.py
See title. It's an easy way to save all parameters with the matrices for now.
=> Write config copy to Labivew matrix directory

.github/pull_request_templates/release.md, docs/todo.rst
This PR adds a PR template for release branches. It will be automatically applied to PRs from branches starting with the string "release", for example "release_v0.1.01".
It also adds instructions in the docs on how to make a new release.
=> Add PR template for releases

Asterix/wfsc/wf_control_functions.py
Just a small add to save the basis used to create the matrix all the time
=> save basis fits

.github/workflows/testing.yml, docs/install.rst
add a simpler install for people who knows 
-> pip install git+https://github.com/johanmazoyer/Asterix.git
=> update the install

Asterix/Example_param_file.ini, Asterix/Param_configspec.ini, Asterix/example_run_asterix.py, Asterix/main_THD.py, Asterix/optics/testbed.py, Asterix/tests/param_file_tests.ini, Asterix/wfsc/correction_loop.py, Asterix/wfsc/estimator.py, Asterix/wfsc/wf_sensing_functions.py, docs/estimation.rst, docs/run_asterix.rst
- Create a function to make actuator probes
- Added a name_DM_to_probe_in_PW parameter to parameter file
- added functions to testbed class to go from an individual DM voltage vector to the testbed DM voltage vector and back (extract an individual DM voltage vector from the testbed DM voltage).
=> Create a function to make actuator probes

Asterix/Example_param_file.ini, Asterix/example_run_asterix.py, Asterix/optics/deformable_mirror.py, Asterix/wfsc/wf_control_functions.py, Asterix/wfsc/wf_sensing_functions.py
A few headers added to model matrices to ensure that they are effectively recalculated in the case of parameter change:
- pushact: added header with DM parameter and recalculate if any parameter changes.
- which in pup: added header with DM parameter, recalculate every time. which in pup is very fast (<0.5s) so it is now remeasured every time to avoid any problem.
- Fourier phase fits file: added header with DM parameter and recalculate if any parameter changes.
Additional change: _filename_active_actu is now read even for generic DM so that we can have a "circular generic DM".
=> Header dm pushact, whichinpup and fourier basis calculation fits

Asterix/main_THD.py, Asterix/optics/deformable_mirror.py, Asterix/utils/save_and_read.py
Keywords saved in all caps to avoid weird errors in fits header comparison
=> Keywords saved in all caps to avoid weird errors in fits header comparison

README.md, docs/index.rst
=> update doc LIRA
