.gitignore, Asterix/save_results.py
While running the example script `Example_Run_Asterix.py`, the four WFS&C example in there threw an error because the lable variable wasn't formatted appropriately. This PR fixes that and the example script now finished without errors.
=> Fix label bug in example script

README.md, source/conf.py, source/index.rst, source/install.rst
Edited by @ivalaginja : Always good to provide a basic description with a PR! :)
Deprecation of `setuptools` command line functionality was introduced here: https://github.com/pypa/setuptools/pull/2824
And a summary of what is happening is given here: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
=> update readme and install section in pdf manual

Asterix/Main_THD.py, Asterix/Optical_System_functions.py, Asterix/THD_quick_invert.py, Asterix/WSC_functions.py, Asterix/correction_loop.py, Asterix/corrector.py, Asterix/estimator.py, Asterix/example_run_asterix.py, Asterix/main_THD.py, Asterix/optical_systems.py, Asterix/phase_amplitude_functions.py, Asterix/processing_functions.py, Asterix/propagation_functions.py, Asterix/save_and_read.py, Asterix/save_results.py, Asterix/tests/test_coronagraph.py, Asterix/tests/test_parameter_file.py, Asterix/tuto_asterix_model.py, notebooks/beginner-tutorial_optical-components-and-systems.ipynb, source/correction.rst, source/create_my_testbed.rst, source/index.rst, source/run_asterix.rst
Class names in Python are written in camel case [according to PEP8](https://peps.python.org/pep-0008/#class-names). Some of the classes in Asterix were already adhering to that, others no. This PR unifies this and removes some obvious comments that repeat the class names.
A summary of Python naming conventions can be found here:
https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html
It seemed like a good time to do this since we just closed all PRs (except for #52 which only changes plotting) before I start working on more substantial changes.
Needs #60 to me merged first.
=> Unify class names in OpticalSystem module

Asterix/main_THD.py, Asterix/wfsc/correction_loop.py
The function `correction_loop()` has a silencing parameter that allows to suppress on-the-fly plotting. Somewhere in the chain while using `runthd2()`, this was hard-coded (in two places). I am pulling it out into the top-level function to be able to access it. Note that this does not change the function signature of `runthd2()` when this is not actively set as it has a default (`False`).
This will also be helpful to set up tests further down the line.
Also fixed some docstrings on the way.
=> Pull out the `silence` keyword to be able to use it everywhere

Asterix/example_run_asterix.py, Asterix/main_THD.py, Asterix/optics/coronagraph.py, Asterix/optics/deformable_mirror.py, Asterix/optics/optical_systems.py, Asterix/optics/phase_amplitude_functions.py, Asterix/optics/pupil.py, Asterix/optics/testbed.py, Asterix/tests/test_utils.py, Asterix/utils/hci_metrics.py, Asterix/utils/save_and_read.py, Asterix/wfsc/correction_loop.py, Asterix/wfsc/corrector.py, Asterix/wfsc/estimator.py, Asterix/wfsc/maskDH.py, Asterix/wfsc/wf_control_functions.py, Asterix/wfsc/wf_sensing_functions.py, source/conf.py, source/correction.rst, source/create_my_testbed.rst, source/estimation.rst, source/run_asterix.rst
Added a save_all_planes_to_fits option to mainTHD2 to help debug (Raphael asked for it). I carefully selected what is saved by default if you activate it to avoid sending thousands of .fits per second:
- Mask
- PW Estimate
- 1 full run through testbed (~17 fits for 1 DM testbed -one before and after each planes more or less-).
What we are **not** saved by default, but can be easily done if adding save_all_planes_to_fits=True individually to these functions:
- PW difference (2*nb_probes*17 fits for 1 DM testbed)
- PW Matrix (nb_probes*17 fits for 1 DM testbed)
- EFC Matrix (nb_actuator*17 fits for 1 DM testbed)
=> Add save all planes option to main

Asterix/__init__.py, Asterix/main_THD.py, Asterix/utils/save_and_read.py, source/run_asterix.rst
Currently, the only way to set the saving location of the output files is by changing the appropriate entry (`Data_dir`) in the configfile. This means that the default location for this is inside the repository, which gets messy easily.
This PR makes the default location the user's home directory as long as the configfile entry is set to `Data_dir = '.'`, where it will automatically create the subfolder `asterix_data`. The user can still use the configfile to set the directory they want the data saved in, so everything stays the same in that regard.
As a plus, people can also set an environment variable on their local machine to control the location of the output data of Asterix, but this is not required.
=> Make default location for output data not inside repo

Asterix/Example_param_file.ini, Asterix/main_THD.py, Asterix/optics/optical_systems.py, Asterix/utils/hci_metrics.py, Asterix/utils/save_and_read.py, Asterix/wfsc/correction_loop.py, source/correction.rst, source/run_asterix.rst
PR for a suggestion:
The current output structure of experiments run by Asterix is as follows:
```bash
Interaction_Matrices
|-- several .fits files
Labview
|-- several .fits files
Model_local
|-- several .fits files
Results
|-- exp_dir1
|-- exp_dir2
|--...
```
where `exp_dir1` and so forth are strings put into the configuration file or passed to the experiment function at runtime. This means that for each new experiment, a new string must be passed manually, otherwise the results will be overwritten.
While this might be fine (although not recommended because you lose the option to compare to previous runs) when debugging, this can be extremely destructive when several different runs are intended to be kept on purpose for good, because it is easy to forget to change the experiment name. …
=> Sort results directories with timestamp

Asterix/Example_param_file.ini, Asterix/main_THD.py, Asterix/wfsc/maskDH.py, notebooks/create_text_arrays.ipynb
During the THD2 meeting today, @rgalicher and Pierre Baudoz were wondering whether we could dig a DH that spells out the text "CNRS" for the demo during the CNRS visit next week, like they did it once with "THD2". This PR adds this possibility.
The text "CNRS" is hard-coded for now but if there is ever another need for a custom DH with a text, this can be adapted. The DH created looks like this on the simulator:
I also added a notebook in which one can play around with how to create the DH mask you want.
=> Add option to use custom-made DH mask with text "CNRS"

Asterix/optics/propagation_functions.py
This introduces an MFT parameter to choose the bit number for the complex arrays in the MFT matrices.
Can be complex128 or complex64. The latter increases the speed of the mft but at the cost of lower precision.
I introduced this change because we are currently discussing  the level of numerical noise of the MFT in PR #97 
The change from complex128 to complex64 was made in PR #80 about speeding up the MFT but was maybe not thought enough, so default in now back to complex128
=> introduce choice of complex bit number in MFT

Asterix/optics/coronagraph.py, Asterix/optics/deformable_mirror.py, Asterix/optics/optical_systems.py, Asterix/utils/hci_metrics.py, Asterix/utils/save_and_read.py
np.int and np.float are now deprecated https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
This cause warnings in the tests. This PR replace np.int -> int and np.float -> float. No more warning when pytest on my machine
=> Fix warnings from pytest

Asterix/optics/propagation_functions.py, Asterix/tests/test_propagations.py, notebooks/coronagraph_propagation.ipynb, notebooks/zoom-in_sampling_coro.ipynb
The zoom-in sampling function was fixed in #101 but it does  not accommodate separate sizes for the pupil and FPM, which is required for use in Asterix. This PR fixes that. I also lowered the test threshold now that it's working better and did minor updates to the notebooks.
=> Enable zoom-in sampling for Asterix

Asterix/optics/optical_systems.py
With parameters lambda0 = 783nm, bw = 30nm, nlam = 3:
**Previous implementation** (wrong): the 3 wl were : [lambda0 - bw/2, lambda0, lambda0 + bw/2] so [768, 783, 798].
**New implementation** (better), we split the BW in small bandwidths of equal sizes small_bw = bw/nlam and we take the centers of each of these small bw. With the same parameters, the 3 wl are : [lambda0 - small_bw, lambda0, lambda0 + small_bw] so [773, 783, 793].
=> Change the WLs to be equally spaced in a large bandwidth

Asterix/wfsc/corrector.py
@rgalicher I transformed the exception in a warning in the number of mode for the testbed :
"Nbmodes_OnTestbed (550) in inversion for THD is probably too high for 1DM. This is just a warning, if you kown what your are doing, press any key to continue"
This is a very special case (CNRS DH won't happen everyday) so this should be just fine.
=> Transform exception in warning for number of modes in THD matrices

Asterix/tests/test_propagations.py
Adding 2 propagation tests:
- Compare that MFT and FFT gives the same results, down to the numerical noise
- Test that MFT-1 [MFT [PUP] ] = Pup, down to the numerical noise
=> Add tests propagation

source/conf.py
Exceptionally bypassing review because very small modification changing only the source documentation to be able to run Read the Docs
=> Install pyan3 in source/conf.py to make it run in read the doc

Asterix/main_THD.py, Asterix/optics/deformable_mirror.py, Asterix/tests/testbed_test.py
Main goal is to create a testbed_test just to test that creating a simple testbed works
Also in this class 2 small modifs:
- a np.float in deformable_mirror.py that was throwing a deprecation error
- in Main_thd, I renamed parameter_file variable in parameter_file_path to be more precise and not confuse it with the parameter_file itself.
=> Testbed tests

Asterix/optics/coronagraph.py, Asterix/utils/save_and_read.py, notebooks/shift_wrapped_vortex.ipynb, notebooks/wv_mask_inclination.ipynb
Replaces #108
This PR adds the option to incline the wrapped vortex phase mask along either of the two axes. Below is an example of inclining it by 50 degrees around the x axis (right), compared to no inclination (left):
I also committed the notebooks here that I used to test this, and in which I ran some tests to investigate the effect of a shifted and/or inclined phase mask.
=> Add optional inclinations to wrapped vortex phase mask

Asterix/optics/testbed.py, Asterix/wfsc/correction_loop.py, Asterix/wfsc/corrector.py, Asterix/wfsc/estimator.py, Asterix/wfsc/wf_control_functions.py, Asterix/wfsc/wf_sensing_functions.py
Something changed in the package or CI setup so that the classes imported for type hinting are now flagged as unused imports, an issue we have not had before. Discovered while working on #124, one failed run here: https://github.com/johanmazoyer/Asterix/actions/runs/3567127502/jobs/5994434054
Changeing the type hints to something more explicit
=> Replace type hints for optical systems to avoid unused import in flake8

Asterix/wfsc/maskDH.py
PR #124 actually broke the full DH. This PR fixes that
Before #124 :
options for DH_side: 'top', 'bottom', 'left', 'right' and all others were default to 'full'
Now: 
options for DH_side: 'top', 'bottom', 'left', 'right, 'full' and all others raise an exception
=> Full DH fixed

Asterix/tests/test_coronagraph.py, Asterix/tests/test_propagations.py
I split up #121 after all since we want to progress on the CI tests.
This PR modifies the test for the "default" coronagraph to include all coronagraph options of Asterix, significantly increasing test coverage. And I adapt the test for the zoom-in sampled propagation function to also test on the wrapped vortex coro, not just on the FQPM.
Notes for later:
- this does *not* change the FQPM default propagation, it sticks with MFTs, but also an artificial perfect coronagraph
- the fact that the FQPM is artifically set to produce zero light means I changed its expected attenuation to 1e-20, which will need to be changed if we ever change the propagation the FQPM uses
- equally, if we ever set the pupils to default to grey pupils, we can improve the expected attenuation factor of tthe WV coro
=> Update coronagraph tests

Asterix/main_THD.py, Asterix/utils/save_and_read.py, Asterix/wfsc/thd_quick_invert.py
I would like to save the matrix files created for the Labview controls to individual sub-folders each time they are generated, with each sub-folder getting a time stamp much like the data result folders. This prevents over-writing when running several simulated experiments sequentially. I also added the coronagraph type to the directory name to have at least some initial info, but I am keeping the file names purposefully simple, leaving it up to the user to rename them as needed, since this will likely always be needed.
The second thing added to the sub-folder name is the short commit hash of the repo version the data has been created with.
This will allow us to create a bunch of hardware-ready matrix directories in one go, and trace which commit they have been created on.
Note how this …
=> Time-stamped sub folders and commit hash for Labview matrices

Asterix/optics/coronagraph.py
See title.
I did this by comparing to the code setup of a commit that creates matrices that work on the testbed and manage to create a DH.
The phase masks look like this:
Left the old commit (213d669b) from fits file including a flip and a rotation, center the correctly rotated phase mask from Asterix to match that, here on this branch, right their difference normalized by the max of the fits-file version (left).
(Note how commit 08b91a is now [79fc551](https://github.com/johanmazoyer/Asterix/pull/145/commits/79fc551edcf252a4cbea6b5dc50753d8b6ae1008) because I rebased.)
This is completely unrelated to the type of propagation, we are going to test matrices generated with this but using MFTs on the hardware. If that works (🤞 ), we can focus on figuring out what's up with our zoom-in sampled …
=> Match WV phase mask orientation on THD2 testbed

Asterix/optics/coronagraph.py, Asterix/optics/optical_systems.py
Some options are not possible if we precalculate the MFT matrices (like introducing an offset in the focal plane in `prop_fpm_regional_sampling`). For this reason, this PR introduce a hardcoded parameter `precalculate_mft_matrices` for all `OpticalSystem`s which allow us to easily go back to the option of recalculating the matrices all the times. This is slower but allow more freedom for  advanced users. 
We pytested both case precalculate_mft_matrices = True and precalculate_mft_matrices = False
precalculate_mft_matrices = True is still the default (faster but you cannot do more advanced stuff in the propagation)
=> Option to pre calculate mft matrices or not

Asterix/Example_param_file.ini, Asterix/optics/coronagraph.py, Asterix/thd2_setups/fqpm_parameters.ini, Asterix/thd2_setups/wrapped_vortex_parameters.ini
Smalls changes to make Vortex easier to use on the testbed:
- Vortex is now use by default in MFT propagation + perfect corono option (at all wl). 
- Adapted the parameter files with more default option for vortex
=> Small vortex upgrade

Asterix/example_run_asterix.py, Asterix/main_THD.py, Asterix/optics/coronagraph.py, Asterix/optics/deformable_mirror.py, Asterix/optics/optical_systems.py, Asterix/optics/propagation_functions.py, Asterix/wfsc/corrector.py, Asterix/wfsc/estimator.py, Asterix/wfsc/wf_control_functions.py, Asterix/wfsc/wf_sensing_functions.py
Option to switch the complex precision "complex128", to "complex64".
This is mostly important for the MFT and the complex exponential. The FFT in numpy does not allow the dtype keyword so I suspect that in that case the change is pretty useless. (the FFT in numpy is used for the angular spectrum propagation that is used for the out of plane DMs). The default stay complex128. 
The option is a 'secret' parameter (not accessible from parameter file to not over fill it). You can access by defining
`model_config['complex_precision'] = 'complex128'`
before the definition of the optical elements of the sytem. For example :
```
config = read_parameter_file(parameter_file_path)
model_config = config["modelconfig"]
model_config['complex_precision'] = 'complex64'
entrance_pupil = Pupil(model_config) …
```
=> Option to change the complex precision

Asterix/wfsc/maskDH.py
Add 2 lines in the mask creation to create a custom mask (e.g. CNRS) with the right orientation :
- For the correct orientation in simulation and in DS9 testbed data
- For the correct orientation on the testbed labview screen for demo
So that we do no have to redo all the time we want to do a demo
=> Custom mask orientation 

Asterix/wfsc/correction_loop.py, Asterix/wfsc/estimator.py, Asterix/wfsc/wf_sensing_functions.py, docs/estimation.rst
Separated estimates fonction in 2 parts :
- estimation.probes() which handle the probing part itself
- estimation.estimate() which does the PW matrix multiplication 
the goal is to make it easier to run on the testbed as only the probing function can be replaced. 
Checked that results were exactly identical to the current master branch.
=> Separate probing and estimation for better integration on testbed

Asterix/Example_param_file.ini, Asterix/example_run_asterix.py, Asterix/main_THD.py, Asterix/wfsc/estimator.py, Asterix/wfsc/wf_control_functions.py, Asterix/wfsc/wf_sensing_functions.py, docs/estimation.rst, docs/install.rst, docs/run_asterix.rst
Added a mode to do Bordé and Traub Probing (see Potier et al 2024 paper for details). Update also the docs
Used this opportunity to rename pw by pwp while keeping the backward compatibility with former parameter file 
Quick comparison with 2 corrections (1 and 2 DM) show it seems to work 
﻿
=> Add Bordé et Traub mode for estimation 

Asterix/optics/deformable_mirror.py, Asterix/optics/testbed.py, Asterix/wfsc/correction_loop.py, Asterix/wfsc/corrector.py, Asterix/wfsc/estimator.py, Asterix/wfsc/wf_control_functions.py
DMs that are declared on the Testbed during initialization but marked as inactive (``DMXX_active = False`` in parameter file) are still accounted in the vector of voltages sent to the DMs. (DMvotage = [DM1 voltage, DM3 Voltage])
Before this PR, inactive DM names were declared (DM objects were created) to the DMs but could not be talked to as the vector of voltages sent to the DMs was only using the other DM voltages
With this PR, the inactive DM names are still declared but during EFC / PW they are not sent command (command always zero). This is a more consistent testbed model in both cases (with 1 or 2 DMs).
If you really want a one DM testbed, you can still remove the other one from initialization
=> Votge vectors now inlcude the inactive DMs actuators

Asterix/main_THD.py, Asterix/optics/testbed.py, Asterix/utils/save_and_read.py, Asterix/wfsc/correction_loop.py, Asterix/wfsc/corrector.py, Asterix/wfsc/estimator.py, Asterix/wfsc/thd_quick_invert.py, Asterix/wfsc/wf_control_functions.py, Asterix/wfsc/wf_sensing_functions.py, docs/install.rst
1) Lot of header change in most fits saved : 
a / Added the config is all saved matrices. Created specific fonctions to identify `name_header_efc_matrix` and `name_header_pwp_matrix` to specifically identify kw important for each matrix. Based on these kw, the matrix are recalculated or not (this is more selective than the name of matrix that was used until now)/ 
b/ Date and hour of saving is also saved in header["date_mat"] 
c/ Finally Added a kw : header["MODELSIM"] = 'asterix' in all matrices
Referenced in this issue in thd-controls package
https://github.com/ivalaginja/thd-controls/issues/132
3) we also save the matrices in the thd-controls format, see 
https://github.com/ivalaginja/thd-controls/issues/129
=> update header matrices + saved thd-control version

Asterix/main_THD.py, Asterix/tests/test_wfsc.py, Asterix/wfsc/correction_loop.py, Asterix/wfsc/corrector.py, Asterix/wfsc/estimator.py, Asterix/wfsc/wf_control_functions.py, docs/correction.rst
The goal is to make Corrector estimation much more independent of the estimator. The full estimator class needed to be called when defining a corrector, but in practice we only used 2 values (the dimension of the estimation and the wavelengths of the estimation). I only pass those 2 parameters. 
I also make it easier to update the mask in update_matrices() function.
=> Remove estimator from corrector

Asterix/optics/deformable_mirror.py, Asterix/utils/processing_functions.py
**added an Avoid_wrapping function in ft_subpixel_shift**
We notice that the sub-pixel shift in fourrier mode was "wrapping" on the other side if close to the edge. This made the push-act array a bit wring because actuators had impact on the other side of the pupil. 
We added an Avoid_wrapping function in ft_subpixel_shift by padding the array with 0s before the FFT shift. We remoce the fourrier option (that allowed the function to take the Fourier transform of the image directly, saving a fourier transofmr in some case) because the size of the entrance array would have to vary depending on the entrance.  
**Remove which in pup fits.** 
The which_in_pup was saved but never read. It is extremely fast to calculate so this is not a problem but if you launch the code several time in parallel …
=> Correction of a few errors in deformable_mirrors.py
